/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oracle_paas_OracleHCMKey */

#ifndef _Included_com_oracle_paas_OracleHCMKey
#define _Included_com_oracle_paas_OracleHCMKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oracle_paas_OracleHCMKey
 * Method:    getOracleHCMurl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oracle_paas_OracleHCMKey_getOracleHCMurl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_oracle_paas_OracleHCMKey
 * Method:    getOracleHCMuser
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oracle_paas_OracleHCMKey_getOracleHCMuser
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_oracle_paas_OracleHCMKey
 * Method:    getOracleHCMpass
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oracle_paas_OracleHCMKey_getOracleHCMpass
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
