/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JOCLApp1 */

#ifndef _Included_JOCLApp1
#define _Included_JOCLApp1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JOCLApp1
 * Method:    callGPU
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JOCLApp1_callGPU
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
